// Updated daily by scheduled task at 5:50 PM Taiwan time
export const DAILY_VIDEO = {
  date: '2026-06-25',
  title: 'Market Microstructure: How Exchanges Really Work',
  channel: 'Econ / Finance Lectures',
  source: 'Academic / CFA Institute',
  tag: 'YouTube',
  url: 'https://www.youtube.com/watch?v=FTeMtc1GTTg',
  topics: ['Bid-ask spread', 'Adverse selection', 'Price impact', 'Dark pools'],
  description: 'The theory behind why spreads exist, how market makers are compensated for risk, and what order flow tells you about price discovery.',
}

// Curated rotation list — scheduled task picks by (dayOfYear % length)
export const VIDEO_LIST = [
  {
    title: 'Low Latency C++ for Fun and Profit',
    channel: 'CppCon',
    source: 'CppCon 2023 — Timur Doumler',
    url: 'https://www.youtube.com/watch?v=NH1Tta7purM',
    topics: ['Memory layout & cache locality', 'Branch prediction', 'Lock-free structures', 'SIMD'],
    description: 'Practical low-latency C++ patterns from production trading systems — cache-friendly design, allocation avoidance, nanosecond profiling.',
  },
  {
    title: 'Mechanical Sympathy: Hardware & Software Working Together',
    channel: 'GOTO Conferences',
    source: 'Martin Thompson — LMAX',
    url: 'https://www.youtube.com/watch?v=MC1EKLQ2Wmg',
    topics: ['CPU pipeline', 'Cache hierarchy', 'Memory barriers', 'Disruptor pattern'],
    description: 'Martin Thompson explains how to write code that works with hardware rather than against it — the mental model behind LMAX Disruptor and ultra-low-latency Java/C++.',
  },
  {
    title: 'Kernel Bypass Networking with DPDK',
    channel: 'Linux Foundation',
    source: 'Linux Plumbers Conference',
    url: 'https://www.youtube.com/results?search_query=dpdk+kernel+bypass+networking+tutorial',
    topics: ['DPDK architecture', 'Poll-mode drivers', 'Zero-copy I/O', 'CPU pinning'],
    description: 'How DPDK bypasses the Linux kernel for packet processing — enables sub-microsecond network I/O critical for market data and order routing.',
  },
  {
    title: 'io_uring: The Next Generation Linux I/O API',
    channel: 'Linux Foundation',
    source: 'Jens Axboe — kernel.dk',
    url: 'https://www.youtube.com/results?search_query=io_uring+jens+axboe+linux+io',
    topics: ['Submission/completion rings', 'Zero syscall I/O', 'Fixed buffers', 'Polling mode'],
    description: 'io_uring fundamentally changes how Linux does async I/O — shared ring buffers between userspace and kernel eliminate system call overhead for network and disk.',
  },
  {
    title: 'High Frequency Trading — How It Works',
    channel: 'Quantopian / QuantConnect',
    source: 'Market structure explainer',
    url: 'https://www.youtube.com/results?search_query=high+frequency+trading+system+design+how+it+works',
    topics: ['Co-location', 'Market making', 'Order types', 'Latency arbitrage'],
    description: 'End-to-end walkthrough of an HFT system — from exchange co-location and feed handlers to order routing and risk checks.',
  },
  {
    title: 'Building a High-Performance Order Book',
    channel: 'CppCon',
    source: 'CppCon — Charles Sherfy',
    url: 'https://www.youtube.com/results?search_query=cppcon+order+book+high+performance+trading',
    topics: ['Price level arrays', 'Cache-line alignment', 'Lock-free updates', 'Memory pools'],
    description: 'Step-by-step implementation of a production-grade limit order book in C++ — data structure choices that keep update latency under 100ns.',
  },
  {
    title: 'FPGA Acceleration in Financial Trading',
    channel: 'Xilinx / AMD',
    source: 'FPGA Developer Forum',
    url: 'https://www.youtube.com/results?search_query=fpga+hft+trading+acceleration+xilinx',
    topics: ['Hardware order book', 'Network-to-strategy pipeline', 'SmartNIC', 'Deterministic latency'],
    description: 'How FPGAs achieve deterministic sub-microsecond latency — from parsing market data in hardware to generating orders without touching the CPU.',
  },
  {
    title: 'TCP Performance Tuning for Low Latency',
    channel: 'Linux Foundation',
    source: 'Networking @Scale',
    url: 'https://www.youtube.com/results?search_query=tcp+performance+tuning+low+latency+linux+kernel',
    topics: ['Nagle algorithm', 'TCP_NODELAY', 'SO_BUSY_POLL', 'IRQ affinity'],
    description: 'Linux TCP stack knobs that matter for trading — disabling Nagle, busy-poll sockets, RPS/RFS tuning, and interrupt coalescing trade-offs.',
  },
  {
    title: 'Aeron: Next-Gen High-Performance Messaging',
    channel: 'Real Logic',
    source: 'Martin Thompson & Todd Montgomery',
    url: 'https://www.youtube.com/results?search_query=aeron+messaging+martin+thompson+high+performance',
    topics: ['Log-structured messaging', 'IPC vs UDP', 'Flow control', 'Zero-copy transport'],
    description: 'Aeron is the messaging layer used in many trading firms — designed from scratch for predictable low latency over UDP and shared memory IPC.',
  },
  {
    title: 'Lock-Free Programming in C++',
    channel: 'CppCon',
    source: 'CppCon — Fedor Pikus',
    url: 'https://www.youtube.com/watch?v=lVBvHbJsg5Y',
    topics: ['Memory ordering', 'CAS operations', 'ABA problem', 'SPSC / MPMC queues'],
    description: 'Comprehensive guide to lock-free data structures — memory model rules, std::atomic pitfalls, and patterns directly applicable to trading system queues.',
  },
  {
    title: 'Chronicle Queue: Persisted Low-Latency Messaging',
    channel: 'OpenHFT',
    source: 'Peter Lawrey — Chronicle Software',
    url: 'https://www.youtube.com/results?search_query=chronicle+queue+low+latency+peter+lawrey',
    topics: ['Memory-mapped files', 'Append-only log', 'Off-heap storage', 'Replication'],
    description: 'Chronicle Queue uses memory-mapped files for persistence with microsecond write latency — architecture and trade-offs for event-sourced trading systems.',
  },
  {
    title: 'Market Microstructure: How Exchanges Really Work',
    channel: 'Econ / Finance Lectures',
    source: 'Academic / CFA Institute',
    url: 'https://www.youtube.com/results?search_query=market+microstructure+order+flow+exchange+mechanics',
    topics: ['Bid-ask spread', 'Adverse selection', 'Price impact', 'Dark pools'],
    description: 'The theory behind why spreads exist, how market makers are compensated for risk, and what order flow tells you about price discovery.',
  },
  {
    title: 'Designing for Extreme Reliability: Lessons from HFT',
    channel: 'StrangeLoop',
    source: 'Strange Loop Conference',
    url: 'https://www.youtube.com/results?search_query=strange+loop+high+frequency+trading+reliability+design',
    topics: ['Hot path isolation', 'Deterministic GC avoidance', 'Kernel tuning', 'Circuit breakers'],
    description: 'Engineering practices from HFT shops — how to design systems where a 10µs spike can cost real money, and the ops culture that enforces it.',
  },
  {
    title: 'Multicast Networking for Market Data',
    channel: 'Arista Networks',
    source: 'Financial Networks Summit',
    url: 'https://www.youtube.com/results?search_query=multicast+market+data+networking+financial+arista',
    topics: ['UDP multicast', 'PIM-SM', 'Packet loss recovery', 'Feed handler design'],
    description: 'How market data is distributed over multicast — why exchanges use UDP, how feed handlers manage sequence gaps, and network topology for co-location.',
  },
  {
    title: 'Solarflare / Onload: Kernel Bypass for Trading',
    channel: 'AMD / Xilinx Networking',
    source: 'Solarflare Developer Day',
    url: 'https://www.youtube.com/results?search_query=solarflare+onload+kernel+bypass+trading+latency',
    topics: ['OpenOnload stack', 'EF_VI API', 'Timestamping', 'TCPDirect'],
    description: 'Solarflare\'s OpenOnload runs a full TCP/IP stack in userspace — how it achieves sub-microsecond socket latency and hardware timestamping for trading.',
  },
]
