export const PROBLEMS = [
  // Arrays & Hashing
  { id: 1,    title: 'Two Sum',                                    difficulty: 'Easy',   topic: 'Arrays & Hashing',  slug: 'two-sum' },
  { id: 49,   title: 'Group Anagrams',                             difficulty: 'Medium', topic: 'Arrays & Hashing',  slug: 'group-anagrams' },
  { id: 347,  title: 'Top K Frequent Elements',                    difficulty: 'Medium', topic: 'Arrays & Hashing',  slug: 'top-k-frequent-elements' },
  { id: 238,  title: 'Product of Array Except Self',               difficulty: 'Medium', topic: 'Arrays & Hashing',  slug: 'product-of-array-except-self' },
  { id: 36,   title: 'Valid Sudoku',                               difficulty: 'Medium', topic: 'Arrays & Hashing',  slug: 'valid-sudoku' },
  { id: 128,  title: 'Longest Consecutive Sequence',               difficulty: 'Medium', topic: 'Arrays & Hashing',  slug: 'longest-consecutive-sequence' },
  { id: 217,  title: 'Contains Duplicate',                         difficulty: 'Easy',   topic: 'Arrays & Hashing',  slug: 'contains-duplicate' },
  { id: 242,  title: 'Valid Anagram',                              difficulty: 'Easy',   topic: 'Arrays & Hashing',  slug: 'valid-anagram' },
  { id: 560,  title: 'Subarray Sum Equals K',                      difficulty: 'Medium', topic: 'Arrays & Hashing',  slug: 'subarray-sum-equals-k' },
  { id: 523,  title: 'Continuous Subarray Sum',                    difficulty: 'Medium', topic: 'Arrays & Hashing',  slug: 'continuous-subarray-sum' },
  // Two Pointers
  { id: 15,   title: '3Sum',                                       difficulty: 'Medium', topic: 'Two Pointers',       slug: 'three-sum' },
  { id: 11,   title: 'Container With Most Water',                  difficulty: 'Medium', topic: 'Two Pointers',       slug: 'container-with-most-water' },
  { id: 42,   title: 'Trapping Rain Water',                        difficulty: 'Hard',   topic: 'Two Pointers',       slug: 'trapping-rain-water' },
  { id: 125,  title: 'Valid Palindrome',                           difficulty: 'Easy',   topic: 'Two Pointers',       slug: 'valid-palindrome' },
  { id: 167,  title: 'Two Sum II',                                 difficulty: 'Medium', topic: 'Two Pointers',       slug: 'two-sum-ii-input-array-is-sorted' },
  { id: 16,   title: '3Sum Closest',                               difficulty: 'Medium', topic: 'Two Pointers',       slug: 'three-sum-closest' },
  // Sliding Window
  { id: 121,  title: 'Best Time to Buy and Sell Stock',            difficulty: 'Easy',   topic: 'Sliding Window',     slug: 'best-time-to-buy-and-sell-stock' },
  { id: 3,    title: 'Longest Substring Without Repeating',        difficulty: 'Medium', topic: 'Sliding Window',     slug: 'longest-substring-without-repeating-characters' },
  { id: 424,  title: 'Longest Repeating Character Replacement',    difficulty: 'Medium', topic: 'Sliding Window',     slug: 'longest-repeating-character-replacement' },
  { id: 76,   title: 'Minimum Window Substring',                   difficulty: 'Hard',   topic: 'Sliding Window',     slug: 'minimum-window-substring' },
  { id: 239,  title: 'Sliding Window Maximum',                     difficulty: 'Hard',   topic: 'Sliding Window',     slug: 'sliding-window-maximum' },
  { id: 567,  title: 'Permutation in String',                      difficulty: 'Medium', topic: 'Sliding Window',     slug: 'permutation-in-string' },
  { id: 209,  title: 'Minimum Size Subarray Sum',                  difficulty: 'Medium', topic: 'Sliding Window',     slug: 'minimum-size-subarray-sum' },
  // Stack
  { id: 20,   title: 'Valid Parentheses',                          difficulty: 'Easy',   topic: 'Stack',              slug: 'valid-parentheses' },
  { id: 155,  title: 'Min Stack',                                  difficulty: 'Medium', topic: 'Stack',              slug: 'min-stack' },
  { id: 150,  title: 'Evaluate Reverse Polish Notation',           difficulty: 'Medium', topic: 'Stack',              slug: 'evaluate-reverse-polish-notation' },
  { id: 22,   title: 'Generate Parentheses',                       difficulty: 'Medium', topic: 'Stack',              slug: 'generate-parentheses' },
  { id: 739,  title: 'Daily Temperatures',                         difficulty: 'Medium', topic: 'Stack',              slug: 'daily-temperatures' },
  { id: 84,   title: 'Largest Rectangle in Histogram',             difficulty: 'Hard',   topic: 'Stack',              slug: 'largest-rectangle-in-histogram' },
  { id: 853,  title: 'Car Fleet',                                  difficulty: 'Medium', topic: 'Stack',              slug: 'car-fleet' },
  { id: 394,  title: 'Decode String',                              difficulty: 'Medium', topic: 'Stack',              slug: 'decode-string' },
  // Binary Search
  { id: 704,  title: 'Binary Search',                              difficulty: 'Easy',   topic: 'Binary Search',      slug: 'binary-search' },
  { id: 74,   title: 'Search a 2D Matrix',                         difficulty: 'Medium', topic: 'Binary Search',      slug: 'search-a-2d-matrix' },
  { id: 875,  title: 'Koko Eating Bananas',                        difficulty: 'Medium', topic: 'Binary Search',      slug: 'koko-eating-bananas' },
  { id: 153,  title: 'Find Minimum in Rotated Sorted Array',       difficulty: 'Medium', topic: 'Binary Search',      slug: 'find-minimum-in-rotated-sorted-array' },
  { id: 33,   title: 'Search in Rotated Sorted Array',             difficulty: 'Medium', topic: 'Binary Search',      slug: 'search-in-rotated-sorted-array' },
  { id: 4,    title: 'Median of Two Sorted Arrays',                difficulty: 'Hard',   topic: 'Binary Search',      slug: 'median-of-two-sorted-arrays' },
  { id: 981,  title: 'Time Based Key-Value Store',                 difficulty: 'Medium', topic: 'Binary Search',      slug: 'time-based-key-value-store' },
  // Linked List
  { id: 206,  title: 'Reverse Linked List',                        difficulty: 'Easy',   topic: 'Linked List',        slug: 'reverse-linked-list' },
  { id: 21,   title: 'Merge Two Sorted Lists',                     difficulty: 'Easy',   topic: 'Linked List',        slug: 'merge-two-sorted-lists' },
  { id: 143,  title: 'Reorder List',                               difficulty: 'Medium', topic: 'Linked List',        slug: 'reorder-list' },
  { id: 19,   title: 'Remove Nth Node From End',                   difficulty: 'Medium', topic: 'Linked List',        slug: 'remove-nth-node-from-end-of-list' },
  { id: 138,  title: 'Copy List with Random Pointer',              difficulty: 'Medium', topic: 'Linked List',        slug: 'copy-list-with-random-pointer' },
  { id: 2,    title: 'Add Two Numbers',                            difficulty: 'Medium', topic: 'Linked List',        slug: 'add-two-numbers' },
  { id: 141,  title: 'Linked List Cycle',                          difficulty: 'Easy',   topic: 'Linked List',        slug: 'linked-list-cycle' },
  { id: 287,  title: 'Find the Duplicate Number',                  difficulty: 'Medium', topic: 'Linked List',        slug: 'find-the-duplicate-number' },
  { id: 146,  title: 'LRU Cache',                                  difficulty: 'Medium', topic: 'Linked List',        slug: 'lru-cache' },
  { id: 23,   title: 'Merge k Sorted Lists',                       difficulty: 'Hard',   topic: 'Linked List',        slug: 'merge-k-sorted-lists' },
  { id: 25,   title: 'Reverse Nodes in k-Group',                   difficulty: 'Hard',   topic: 'Linked List',        slug: 'reverse-nodes-in-k-group' },
  // Trees
  { id: 226,  title: 'Invert Binary Tree',                         difficulty: 'Easy',   topic: 'Trees',              slug: 'invert-binary-tree' },
  { id: 104,  title: 'Maximum Depth of Binary Tree',               difficulty: 'Easy',   topic: 'Trees',              slug: 'maximum-depth-of-binary-tree' },
  { id: 543,  title: 'Diameter of Binary Tree',                    difficulty: 'Easy',   topic: 'Trees',              slug: 'diameter-of-binary-tree' },
  { id: 110,  title: 'Balanced Binary Tree',                       difficulty: 'Easy',   topic: 'Trees',              slug: 'balanced-binary-tree' },
  { id: 100,  title: 'Same Tree',                                  difficulty: 'Easy',   topic: 'Trees',              slug: 'same-tree' },
  { id: 235,  title: 'Lowest Common Ancestor of BST',              difficulty: 'Medium', topic: 'Trees',              slug: 'lowest-common-ancestor-of-a-binary-search-tree' },
  { id: 102,  title: 'Binary Tree Level Order Traversal',          difficulty: 'Medium', topic: 'Trees',              slug: 'binary-tree-level-order-traversal' },
  { id: 199,  title: 'Binary Tree Right Side View',                difficulty: 'Medium', topic: 'Trees',              slug: 'binary-tree-right-side-view' },
  { id: 98,   title: 'Validate Binary Search Tree',                difficulty: 'Medium', topic: 'Trees',              slug: 'validate-binary-search-tree' },
  { id: 230,  title: 'Kth Smallest Element in BST',               difficulty: 'Medium', topic: 'Trees',              slug: 'kth-smallest-element-in-a-bst' },
  { id: 105,  title: 'Construct Binary Tree from Preorder/Inorder',difficulty: 'Medium', topic: 'Trees',              slug: 'construct-binary-tree-from-preorder-and-inorder-traversal' },
  { id: 124,  title: 'Binary Tree Maximum Path Sum',               difficulty: 'Hard',   topic: 'Trees',              slug: 'binary-tree-maximum-path-sum' },
  { id: 297,  title: 'Serialize and Deserialize Binary Tree',      difficulty: 'Hard',   topic: 'Trees',              slug: 'serialize-and-deserialize-binary-tree' },
  // Heap
  { id: 703,  title: 'Kth Largest Element in a Stream',           difficulty: 'Easy',   topic: 'Heap',               slug: 'kth-largest-element-in-a-stream' },
  { id: 1046, title: 'Last Stone Weight',                          difficulty: 'Easy',   topic: 'Heap',               slug: 'last-stone-weight' },
  { id: 973,  title: 'K Closest Points to Origin',                 difficulty: 'Medium', topic: 'Heap',               slug: 'k-closest-points-to-origin' },
  { id: 215,  title: 'Kth Largest Element in an Array',            difficulty: 'Medium', topic: 'Heap',               slug: 'kth-largest-element-in-an-array' },
  { id: 621,  title: 'Task Scheduler',                             difficulty: 'Medium', topic: 'Heap',               slug: 'task-scheduler' },
  { id: 295,  title: 'Find Median from Data Stream',               difficulty: 'Hard',   topic: 'Heap',               slug: 'find-median-from-data-stream' },
  // Backtracking
  { id: 78,   title: 'Subsets',                                    difficulty: 'Medium', topic: 'Backtracking',       slug: 'subsets' },
  { id: 39,   title: 'Combination Sum',                            difficulty: 'Medium', topic: 'Backtracking',       slug: 'combination-sum' },
  { id: 46,   title: 'Permutations',                               difficulty: 'Medium', topic: 'Backtracking',       slug: 'permutations' },
  { id: 90,   title: 'Subsets II',                                 difficulty: 'Medium', topic: 'Backtracking',       slug: 'subsets-ii' },
  { id: 40,   title: 'Combination Sum II',                         difficulty: 'Medium', topic: 'Backtracking',       slug: 'combination-sum-ii' },
  { id: 79,   title: 'Word Search',                                difficulty: 'Medium', topic: 'Backtracking',       slug: 'word-search' },
  { id: 131,  title: 'Palindrome Partitioning',                    difficulty: 'Medium', topic: 'Backtracking',       slug: 'palindrome-partitioning' },
  { id: 17,   title: 'Letter Combinations of a Phone Number',      difficulty: 'Medium', topic: 'Backtracking',       slug: 'letter-combinations-of-a-phone-number' },
  { id: 51,   title: 'N-Queens',                                   difficulty: 'Hard',   topic: 'Backtracking',       slug: 'n-queens' },
  // Graphs
  { id: 200,  title: 'Number of Islands',                          difficulty: 'Medium', topic: 'Graphs',             slug: 'number-of-islands' },
  { id: 695,  title: 'Max Area of Island',                         difficulty: 'Medium', topic: 'Graphs',             slug: 'max-area-of-island' },
  { id: 133,  title: 'Clone Graph',                                difficulty: 'Medium', topic: 'Graphs',             slug: 'clone-graph' },
  { id: 207,  title: 'Course Schedule',                            difficulty: 'Medium', topic: 'Graphs',             slug: 'course-schedule' },
  { id: 210,  title: 'Course Schedule II',                         difficulty: 'Medium', topic: 'Graphs',             slug: 'course-schedule-ii' },
  { id: 417,  title: 'Pacific Atlantic Water Flow',                difficulty: 'Medium', topic: 'Graphs',             slug: 'pacific-atlantic-water-flow' },
  { id: 127,  title: 'Word Ladder',                                difficulty: 'Hard',   topic: 'Graphs',             slug: 'word-ladder' },
  { id: 994,  title: 'Rotting Oranges',                            difficulty: 'Medium', topic: 'Graphs',             slug: 'rotting-oranges' },
  { id: 130,  title: 'Surrounded Regions',                         difficulty: 'Medium', topic: 'Graphs',             slug: 'surrounded-regions' },
  { id: 684,  title: 'Redundant Connection',                       difficulty: 'Medium', topic: 'Graphs',             slug: 'redundant-connection' },
  // Advanced Graphs
  { id: 743,  title: 'Network Delay Time',                         difficulty: 'Medium', topic: 'Advanced Graphs',    slug: 'network-delay-time' },
  { id: 778,  title: 'Swim in Rising Water',                       difficulty: 'Hard',   topic: 'Advanced Graphs',    slug: 'swim-in-rising-water' },
  { id: 787,  title: 'Cheapest Flights Within K Stops',            difficulty: 'Medium', topic: 'Advanced Graphs',    slug: 'cheapest-flights-within-k-stops' },
  { id: 332,  title: 'Reconstruct Itinerary',                      difficulty: 'Hard',   topic: 'Advanced Graphs',    slug: 'reconstruct-itinerary' },
  // 1D DP
  { id: 70,   title: 'Climbing Stairs',                            difficulty: 'Easy',   topic: '1D DP',              slug: 'climbing-stairs' },
  { id: 746,  title: 'Min Cost Climbing Stairs',                   difficulty: 'Easy',   topic: '1D DP',              slug: 'min-cost-climbing-stairs' },
  { id: 198,  title: 'House Robber',                               difficulty: 'Medium', topic: '1D DP',              slug: 'house-robber' },
  { id: 213,  title: 'House Robber II',                            difficulty: 'Medium', topic: '1D DP',              slug: 'house-robber-ii' },
  { id: 5,    title: 'Longest Palindromic Substring',              difficulty: 'Medium', topic: '1D DP',              slug: 'longest-palindromic-substring' },
  { id: 91,   title: 'Decode Ways',                                difficulty: 'Medium', topic: '1D DP',              slug: 'decode-ways' },
  { id: 322,  title: 'Coin Change',                                difficulty: 'Medium', topic: '1D DP',              slug: 'coin-change' },
  { id: 152,  title: 'Maximum Product Subarray',                   difficulty: 'Medium', topic: '1D DP',              slug: 'maximum-product-subarray' },
  { id: 139,  title: 'Word Break',                                 difficulty: 'Medium', topic: '1D DP',              slug: 'word-break' },
  { id: 300,  title: 'Longest Increasing Subsequence',             difficulty: 'Medium', topic: '1D DP',              slug: 'longest-increasing-subsequence' },
  { id: 416,  title: 'Partition Equal Subset Sum',                 difficulty: 'Medium', topic: '1D DP',              slug: 'partition-equal-subset-sum' },
  // 2D DP
  { id: 62,   title: 'Unique Paths',                               difficulty: 'Medium', topic: '2D DP',              slug: 'unique-paths' },
  { id: 1143, title: 'Longest Common Subsequence',                 difficulty: 'Medium', topic: '2D DP',              slug: 'longest-common-subsequence' },
  { id: 309,  title: 'Best Time to Buy/Sell with Cooldown',        difficulty: 'Medium', topic: '2D DP',              slug: 'best-time-to-buy-and-sell-stock-with-cooldown' },
  { id: 518,  title: 'Coin Change II',                             difficulty: 'Medium', topic: '2D DP',              slug: 'coin-change-ii' },
  { id: 494,  title: 'Target Sum',                                 difficulty: 'Medium', topic: '2D DP',              slug: 'target-sum' },
  { id: 72,   title: 'Edit Distance',                              difficulty: 'Medium', topic: '2D DP',              slug: 'edit-distance' },
  { id: 312,  title: 'Burst Balloons',                             difficulty: 'Hard',   topic: '2D DP',              slug: 'burst-balloons' },
  { id: 10,   title: 'Regular Expression Matching',                difficulty: 'Hard',   topic: '2D DP',              slug: 'regular-expression-matching' },
  // Greedy
  { id: 53,   title: 'Maximum Subarray',                           difficulty: 'Medium', topic: 'Greedy',             slug: 'maximum-subarray' },
  { id: 55,   title: 'Jump Game',                                  difficulty: 'Medium', topic: 'Greedy',             slug: 'jump-game' },
  { id: 45,   title: 'Jump Game II',                               difficulty: 'Medium', topic: 'Greedy',             slug: 'jump-game-ii' },
  { id: 134,  title: 'Gas Station',                                difficulty: 'Medium', topic: 'Greedy',             slug: 'gas-station' },
  { id: 763,  title: 'Partition Labels',                           difficulty: 'Medium', topic: 'Greedy',             slug: 'partition-labels' },
  { id: 678,  title: 'Valid Parenthesis String',                   difficulty: 'Medium', topic: 'Greedy',             slug: 'valid-parenthesis-string' },
  // Intervals
  { id: 57,   title: 'Insert Interval',                            difficulty: 'Medium', topic: 'Intervals',          slug: 'insert-interval' },
  { id: 56,   title: 'Merge Intervals',                            difficulty: 'Medium', topic: 'Intervals',          slug: 'merge-intervals' },
  { id: 435,  title: 'Non-overlapping Intervals',                  difficulty: 'Medium', topic: 'Intervals',          slug: 'non-overlapping-intervals' },
  { id: 253,  title: 'Meeting Rooms II',                           difficulty: 'Medium', topic: 'Intervals',          slug: 'meeting-rooms-ii' },
  { id: 452,  title: 'Min Arrows to Burst Balloons',               difficulty: 'Medium', topic: 'Intervals',          slug: 'minimum-number-of-arrows-to-burst-balloons' },
  // Math & Geometry
  { id: 48,   title: 'Rotate Image',                               difficulty: 'Medium', topic: 'Math & Geometry',    slug: 'rotate-image' },
  { id: 54,   title: 'Spiral Matrix',                              difficulty: 'Medium', topic: 'Math & Geometry',    slug: 'spiral-matrix' },
  { id: 73,   title: 'Set Matrix Zeroes',                          difficulty: 'Medium', topic: 'Math & Geometry',    slug: 'set-matrix-zeroes' },
  { id: 202,  title: 'Happy Number',                               difficulty: 'Easy',   topic: 'Math & Geometry',    slug: 'happy-number' },
  { id: 50,   title: 'Pow(x, n)',                                  difficulty: 'Medium', topic: 'Math & Geometry',    slug: 'powx-n' },
  // Bit Manipulation
  { id: 136,  title: 'Single Number',                              difficulty: 'Easy',   topic: 'Bit Manipulation',   slug: 'single-number' },
  { id: 191,  title: 'Number of 1 Bits',                           difficulty: 'Easy',   topic: 'Bit Manipulation',   slug: 'number-of-1-bits' },
  { id: 338,  title: 'Counting Bits',                              difficulty: 'Easy',   topic: 'Bit Manipulation',   slug: 'counting-bits' },
  { id: 190,  title: 'Reverse Bits',                               difficulty: 'Easy',   topic: 'Bit Manipulation',   slug: 'reverse-bits' },
  { id: 268,  title: 'Missing Number',                             difficulty: 'Easy',   topic: 'Bit Manipulation',   slug: 'missing-number' },
  { id: 371,  title: 'Sum of Two Integers',                        difficulty: 'Medium', topic: 'Bit Manipulation',   slug: 'sum-of-two-integers' },
]
